import { part1, part2 } from "."
import { describe, it, expect } from "vitest"

describe("test", async () => {
  it("runs part1", () => {
    expect(part1()).toEqual(1717)
  })

  it("runs part2", async () => {
    expect(part2()).toEqual(231507396180012)
  })

  describe("unit tests", () => {
    const testInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

    it("part 1", () => {
      expect(part1(testInput)).toEqual(21)
    })

    it("part 2", () => {
      expect(part2(testInput)).toEqual(40)
    })
  })
})
